workflow:
  rules:
    - if: $CI_COMMIT_BRANCH


stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  # Use shorter path to avoid Windows path length issues
  GRADLE_USER_HOME: "C:\\gc"

before_script:
  - git config core.longpaths true
  - git clean -fdx
  - java -version
  - .\gradlew.bat --version

build:
  stage: build
  script:
    - .\gradlew.bat clean assemble --no-daemon
  artifacts:
    paths:
      - build/libs/
    expire_in: 1 week

test:
  stage: test
  script:
    - .\gradlew.bat test --no-daemon
  artifacts:
    when: always
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
    paths:
      - build/test-results/
      - build/reports/

