# --- Main Database Config
spring.r2dbc.url=r2dbc:postgresql://host.docker.internal:5432/appetit_staging
spring.r2dbc.username=appetit_staging_user
spring.r2dbc.password=${DB_PASSWORD}

# --- Migrations ---
spring.flyway.url=jdbc:postgresql://host.docker.internal:5432/appetit_staging
spring.flyway.user=appetit_staging_user
spring.flyway.password=${DB_PASSWORD}

