spring.application.name=demo
springdoc.swagger-ui.path=/swagger-ui

# --- Main Database Config
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/appetit
spring.r2dbc.username=postgres
spring.r2dbc.password=K#3czmMApApB3sQE

# --- Migrations ---
spring.flyway.url=jdbc:postgresql://localhost:5432/appetit
spring.flyway.user=postgres
spring.flyway.password=K#3czmMApApB3sQE
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.enabled=true

spring.rsocket.server.mapping-path=/socket
spring.rsocket.server.transport=websocket
